Fix package check errors
Errors running `python setup.py check -r -s` due to required
metadata for the package caused by having 'author' set but
not 'author-email'.

Full error is:

```
python setup.py check -r -s
running check
warning: check: missing meta-data: if 'author' supplied, 'author_email' must be
supplied too

error: The docutils package is needed.
```

This updates both author and author-email to be consistent
with the values used in other OpenStack projects.

Change-Id: Icdcb9b9328e361ba4883af5b464c9968f72607e8